import time
from playsound import playsound
from threading import Thread
import os
os.system('cls')
def play():
    playsound("1.wav")
def lyric1():
    print("Playing : somebody pleasure")
    time.sleep(3)
    print("i've got", end=' ',flush=True) 
    time.sleep(1.5)
    print("to take", end=' ',flush=True)
    time.sleep(1.5)
    print("me away", end=' ',flush=True)
    time.sleep(1.5)
    print("from all", end=' ',flush=True)
    time.sleep(1)
    print("sadness", end=' ',flush=True)
    time.sleep(2)
    os.system('cls')
    print("Playing : somebody pleasure")
    print("stich all", end=' ',flush=True)
    time.sleep(1.5)
    print("my wounds", end=' ',flush=True)
    time.sleep(1)
    print("confess all", end=' ',flush=True)
    time.sleep(0.8)
    print("the sins", end=' ',flush=True)
    time.sleep(0.8)
    print("and took all", end=' ',flush=True)
    time.sleep(0.7)
    print("my insecure")
    time.sleep(1.5)
    os.system('cls')
    print("Playing : somebody pleasure")
    print("when will i", end=' ',flush=True) 
    time.sleep(3)
    print("get the love", end=' ',flush=True) 
    time.sleep(1)
    print("that", end=' ',flush=True) 
    time.sleep(0.5)
    print("is", end=' ',flush=True)
    time.sleep(0.4)
    print("so", end=' ',flush=True)
    time.sleep(0.3)
    print("pure?", end=' ',flush=True)
    time.sleep(2.5)
    os.system('cls')
    print("Playing : some body pleasure")
    print("gotta have", end=' ',flush=True)
    time.sleep(0.8)
    print("to always", end=' ',flush=True)
    time.sleep(0.7)
    print("make sure", end=' ',flush=True)
    time.sleep(1)
    os.system('cls')
    print("Playing : somebody pleasure")
    print("that i'm not", end=' ',flush=True)
    time.sleep(0.8)
    print("just somebody", end=' ',flush=True)
    time.sleep(0.8)
    print("pleasure", end=' ',flush=True)
t1 = Thread(target=play)
t1.start()
t2 = Thread(target=lyric1)
t2.start()