import time
from playsound import playsound
from threading import Thread
import os
os.system('cls')
def play():
    playsound("2.wav")
def lyric1():
    print("Playing : badut")
    time.sleep(2)
    print("seperti", end=' ',flush=True) 
    time.sleep(0.8)
    print("dilaguku", end=' ',flush=True)
    time.sleep(0.8)
    print("yang pertama", end=' ',flush=True)
    time.sleep(1)
    os.system('cls')
    print("Playing : badut")
    print("aku", end=' ',flush=True)
    time.sleep(2)
    print("menangis", end=' ',flush=True)
    time.sleep(2)
    print("meminta", end=' ',flush=True)
    time.sleep(1.2)
    print("didengar", end=' ',flush=True)
    time.sleep(1.5)
    print("olehmu", end=' ',flush=True)
    time.sleep(5)
    os.system('cls')
    print("Playing : badut")
    print("tak apa", end=' ',flush=True)
    time.sleep(1)
    print("jika", end=' ',flush=True)
    time.sleep(0.7)
    print("ku tak", end=' ',flush=True)
    time.sleep(0.7)
    print("bahagia", end=' ',flush=True)
    time.sleep(0.8)
    os.system('cls')
    print("Playing : badut")
    print("tak apa", end=' ',flush=True)
    time.sleep(0.7)
    print("jika" , end=' ',flush=True)
    time.sleep(0.8)
    print("kuharus" , end=' ',flush=True)
    time.sleep(0.8)
    print("bermuka" , end=' ',flush=True)
    time.sleep(0.8)
    print("dua" , end=' ',flush=True)
    time.sleep(1)
    os.system('cls')
    print("Playing : badut")
    print("tak apa", end=' ',flush=True) 
    time.sleep(1)
    print("karna", end=' ',flush=True) 
    time.sleep(1)
    print("mungkin", end=' ',flush=True) 
    time.sleep(0.8)
    print("ku tak", end=' ',flush=True)
    time.sleep(0.7)
    print("pantas", end=' ',flush=True)
    time.sleep(0.7)
    print("bahagia", end=' ',flush=True)
    time.sleep(4)
    os.system('cls')
    print("Playing : badut")
    print("tak apa", end=' ',flush=True)
    time.sleep(1)
    print("jika", end=' ',flush=True)
    time.sleep(0.7)
    print("aku", end=' ',flush=True)
    time.sleep(0.7)
    print("terluka", end=' ',flush=True)
    time.sleep(0.7)
    os.system('cls')
    print("Playing : badut")
    print("tak apa", end=' ',flush=True)
    time.sleep(1)
    print("jika", end=' ',flush=True)
    time.sleep(0.7)
    print("kutempatkan", end=' ',flush=True)
    time.sleep(0.7)
    print("kau", end=' ',flush=True)
    time.sleep(0.8)
    print("dikursi", end=' ',flush=True)
    time.sleep(0.8)
    print("utama", end=' ',flush=True)
    time.sleep(1)
    os.system('cls')
    print("Playing : badut")
    print("", end=' ',flush=True)
t1 = Thread(target=play)
t1.start()
t2 = Thread(target=lyric1)
t2.start()